language: python
dist: jammy  # Use Ubuntu 22.04

python:
  - "3.12"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test

after_script:
  - echo "--- Starting after_success stage ---"

  # Step 1: List all files in the current directory.
  # We need to see if the '.coverage' file exists.
  - echo "Listing files in root directory:"
  - ls -la
  
  # Step 2: Run the coveralls command with verbose logging.
  - echo "Attempting to submit coverage report..."
  - coveralls debug --service=travis-ci
