language: python
dist: jammy  # Use Ubuntu 22.04

python:
  - "3.12"

before_script:
  - echo "--- Checking Environment Variables ---"
  - env | sort # 'sort' makes the output alphabetical and easier to read
  - echo "------------------------------------"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py test

after_script:
  - coveralls -v --service=travis-ci --repo_token=$COVERALLS_REPO_TOKEN
